export const user = {
  image:
    'https://i.pinimg.com/originals/68/75/0d/68750de880f7d7c47961490c18c58e5a.jpg',
  firstName: 'Course',
  lastName: 'Square',
  email: 'som.sanga@gmail.com',
};

var date = new Date();

export const courses = [
  {
    id: '1',
    title: 'Whatever course',
    author: 'นันทิกานต์ ประสงค์ทบ',
    expiriedDate: date.setDate(date.getDate() + 7),
    percentage: 30,
    image:
      'https://www.classcentral.com/report/wp-content/uploads/2020/06/top-100-course-pandemic.png',
    totalMins: 89,
    price: '1500',
    category: ['ภาษา', 'คนทำงาน'],
  },
  {
    id: '2',
    title: 'Whatever course',
    author: 'วุฒิพงศ์ นิ่มอ่อน',
    expiriedDate: date.setDate(date.getDate() + 15),
    percentage: 54,
    image:
      'https://www.classcentral.com/report/wp-content/uploads/2020/04/learn-for-free-coronavirus-1024x512.png',
    totalMins: 120,
    totalMins: 89,
    price: '1800',
    category: ['เตรียมสอบ', 'เนื้อหาในห้องเรียน'],
  },
  {
    id: '3',
    title: 'ภาษาอังกฤษในชีวิตประจำวัน',
    author: 'ชไมพร แสงจันทร์',
    expiriedDate: date.setDate(date.getDate() + 35),
    percentage: 65,
    image:
      'https://image.freepik.com/free-vector/flat-landing-page-template-book-library_9209-1914.jpg',
    totalMins: 120,
    price: '1400',
    category: ['ธุรกิจและการทำงาน', 'ไลท์สไตส์'],
  },
  {
    id: '4',
    title: 'ภาษาญี่ปุ่นเบื้องต้น',
    author: 'あおい',
    expiriedDate: date.setDate(date.getDate() + 25),
    percentage: 95,
    image:
      'https://thumbs.dreamstime.com/z/student-studying-internet-vector-web-concept-distance-learning-system-e-learning-easy-to-use-website-banner-landing-142267635.jpg',
    totalMins: 120,
    price: '2500',
    category: ['ไอทีและซอร์ฟแวร์', 'ภาษา'],
  },
];

export const expiriedCourses = [
  {
    id: '1',
    title: 'ภาษาอังกฤษในชีวิตประจำวัน',
    author: 'ชไมพร แสงจันทร์',
    expiriedDate: date.setDate(date.getDate() - 21),
    percentage: 65,
    image: 'https://pgim.cmb.ac.lk/wp-content/uploads/2020/03/learn.png',
    totalMins: 78,
    leftVideos: 8,
  },
  {
    id: '2',
    title: 'การขับร้องเพลงสากล',
    author: 'あおい',
    expiriedDate: date.setDate(date.getDate() + 20),
    percentage: 75,
    image:
      'https://www.classcentral.com/report/wp-content/uploads/2020/04/learn-for-free-coronavirus-1024x512.png',
    totalMins: 114,
    leftVideos: 4,
  },
];

export const course = {
  author: {
    about: null,
    email: 'info@smartcitythailand.or.th',
    imageProfile: null,
    name: 'Smart City Thailand',
    phone: null,
    website: null,
  },
  documents: [
    {
      id: 7492,
      path: 'https://s1-dev.coursesquare.com/data/uploads/courses/4312/material/01_DEPA_Smart_City_Introduction.pdf',
      title: '01_DEPA_Smart_City_Introduction.pdf',
    },
    {
      id: 7493,
      path: 'https://s1-dev.coursesquare.com/data/uploads/courses/4312/material/02_DEPA_Infrastructure_and_Smart_City_Development.pdf',
      title: '02_DEPA_Infrastructure_and_Smart_City_Development.pdf',
    },
    {
      id: 7494,
      path: 'https://s1-dev.coursesquare.com/data/uploads/courses/4312/material/03_DEPA_Smart_City_and_Big_Data_noVideo.pdf',
      title: '03_DEPA_Smart_City_and_Big_Data_noVideo.pdf',
    },
    {
      id: 7495,
      path: 'https://s1-dev.coursesquare.com/data/uploads/courses/4312/material/04_DEPA_Citizen_at_The_Center.pdf',
      title: '04_DEPA_Citizen_at_The_Center.pdf',
    },
    {
      id: 7496,
      path: 'https://s1-dev.coursesquare.com/data/uploads/courses/4312/material/05_DEPA_Technology_SmartCity_and_You.pdf',
      title: '05_DEPA_Technology_SmartCity_and_You.pdf',
    },
    {
      id: 7497,
      path: 'https://s1-dev.coursesquare.com/data/uploads/courses/4312/material/06_DEPA_Feasibilities_Study_in_90_mins.pdf',
      title: '06_DEPA_Feasibilities_Study_in_90_mins.pdf',
    },
    {
      id: 7498,
      path: 'https://s1-dev.coursesquare.com/data/uploads/courses/4312/material/07_DEPA_Smart_City_Feedback.pdf',
      title: '07_DEPA_Smart_City_Feedback.pdf',
    },
  ],
  expiriedDate: '2120-07-30T11:50:02-04:00',
  id: 4312,
  image:
    'https://d10nvwdadbt5z0.cloudfront.net/data/uploads/courses/4312/images/depa_fun_smart_city_thumbnail.jpg',
  lessons: [
    {
      id: 56251,
      lecFreeFlag: 1,
      lecId: 56251,
      lecName: 'เกริ่นนำ',
      lecType: 'VIDEO',
      modId: 10027,
      modOrder: 0,
      title: 'เกริ่นนำ',
    },
    {
      id: 56252,
      lecFreeFlag: 0,
      lecId: 56252,
      lecName: 'ทำไมต้องพัฒนาเมืองอัจฉริยะ',
      lecType: 'VIDEO',
      modId: 10027,
      modOrder: 0,
      title: 'ทำไมต้องพัฒนาเมืองอัจฉริยะ',
    },
    {
      id: 56253,
      lecFreeFlag: 0,
      lecId: 56253,
      lecName: 'ความหมายของเมืองอัจฉริยะ',
      lecType: 'VIDEO',
      modId: 10027,
      modOrder: 0,
      title: 'ความหมายของเมืองอัจฉริยะ',
    },
    {
      id: 56254,
      lecFreeFlag: 0,
      lecId: 56254,
      lecName: 'แนวทางการพัฒนาเมืองอัจฉริยะ ช่วงที่ 1',
      lecType: 'VIDEO',
      modId: 10027,
      modOrder: 0,
      title: 'แนวทางการพัฒนาเมืองอัจฉริยะ ช่วงที่ 1',
    },
    {
      id: 56255,
      lecFreeFlag: 0,
      lecId: 56255,
      lecName: 'แนวทางการพัฒนาเมืองอัจฉริยะ ช่วงที่ 2',
      lecType: 'VIDEO',
      modId: 10027,
      modOrder: 0,
      title: 'แนวทางการพัฒนาเมืองอัจฉริยะ ช่วงที่ 2',
    },
    {
      id: 56256,
      lecFreeFlag: 1,
      lecId: 56256,
      lecName: 'เกริ่นนำ เรื่อง การวางแผนโครงสร้างสร้างเมืองอัจฉริยะและยั่งยืน',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'เกริ่นนำ เรื่อง การวางแผนโครงสร้างสร้างเมืองอัจฉริยะและยั่งยืน',
    },
    {
      id: 56257,
      lecFreeFlag: 0,
      lecId: 56257,
      lecName: 'จุดเริ่มต้นของการพัฒนาเมืองอัจฉริยะและยั่งยืน',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'จุดเริ่มต้นของการพัฒนาเมืองอัจฉริยะและยั่งยืน',
    },
    {
      id: 56258,
      lecFreeFlag: 0,
      lecId: 56258,
      lecName: 'ความเข้าใจในการพัฒนาเมืองอัจฉริยะ ตอนที่ 1',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'ความเข้าใจในการพัฒนาเมืองอัจฉริยะ ตอนที่ 1',
    },
    {
      id: 56259,
      lecFreeFlag: 0,
      lecId: 56259,
      lecName: 'การบูรณาการโครงสร้างพื้นฐาน และการพัฒนาเมืองอัจฉริยะ',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'การบูรณาการโครงสร้างพื้นฐาน และการพัฒนาเมืองอัจฉริยะ',
    },
    {
      id: 56260,
      lecFreeFlag: 0,
      lecId: 56260,
      lecName: 'กรณีศึกษาของเมืองอัจฉริยะที่ประสบความสําเร็จ กรุงอัมสเตอร์ดัม',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'กรณีศึกษาของเมืองอัจฉริยะที่ประสบความสําเร็จ กรุงอัมสเตอร์ดัม',
    },
    {
      id: 56261,
      lecFreeFlag: 0,
      lecId: 56261,
      lecName:
        'การบูรณาการแผนเมืองอัจฉริยะเพื่อส่งเสริม การพัฒนาสู่เมืองมหาวิทยาลัยอย่างยั่งยืน ตอนที่ 1',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title:
        'การบูรณาการแผนเมืองอัจฉริยะเพื่อส่งเสริม การพัฒนาสู่เมืองมหาวิทยาลัยอย่างยั่งยืน ตอนที่ 1',
    },
    {
      id: 56262,
      lecFreeFlag: 0,
      lecId: 56262,
      lecName: 'สรุป เรื่อง การวางแผนโครงสร้างสร้างเมืองอัจฉริยะและยั่งยืน',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'สรุป เรื่อง การวางแผนโครงสร้างสร้างเมืองอัจฉริยะและยั่งยืน',
    },
    {
      id: 56323,
      lecFreeFlag: 0,
      lecId: 56323,
      lecName: 'ความเข้าใจในการพัฒนาเมืองอัจฉริยะ ตอนที่ 2',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'ความเข้าใจในการพัฒนาเมืองอัจฉริยะ ตอนที่ 2',
    },
    {
      id: 56324,
      lecFreeFlag: 0,
      lecId: 56324,
      lecName: 'กรณีศึกษาของเมืองอัจฉริยะที่ประสบความสําเร็จ นครดูไบ',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'กรณีศึกษาของเมืองอัจฉริยะที่ประสบความสําเร็จ นครดูไบ',
    },
    {
      id: 56325,
      lecFreeFlag: 0,
      lecId: 56325,
      lecName: 'กรณีศึกษาของเมืองอัจฉริยะที่ประสบความสําเร็จ กรุงโซล',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title: 'กรณีศึกษาของเมืองอัจฉริยะที่ประสบความสําเร็จ กรุงโซล',
    },
    {
      id: 56326,
      lecFreeFlag: 0,
      lecId: 56326,
      lecName:
        'การบูรณาการแผนเมืองอัจฉริยะเพื่อส่งเสริม การพัฒนาสู่เมืองมหาวิทยาลัยอย่างยั่งยืน ตอนที่ 2',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title:
        'การบูรณาการแผนเมืองอัจฉริยะเพื่อส่งเสริม การพัฒนาสู่เมืองมหาวิทยาลัยอย่างยั่งยืน ตอนที่ 2',
    },
    {
      id: 56327,
      lecFreeFlag: 0,
      lecId: 56327,
      lecName:
        'การบูรณาการแผนเมืองอัจฉริยะเพื่อส่งเสริม การพัฒนาสู่เมืองมหาวิทยาลัยอย่างยั่งยืน ตอนที่ 3',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title:
        'การบูรณาการแผนเมืองอัจฉริยะเพื่อส่งเสริม การพัฒนาสู่เมืองมหาวิทยาลัยอย่างยั่งยืน ตอนที่ 3',
    },
    {
      id: 56328,
      lecFreeFlag: 0,
      lecId: 56328,
      lecName:
        'การบูรณาการแผนเมืองอัจฉริยะเพื่อส่งเสริม การพัฒนาสู่เมืองมหาวิทยาลัยอย่างยั่งยืน ตอนที่ 4',
      lecType: 'VIDEO',
      modId: 10028,
      modOrder: 1,
      title:
        'การบูรณาการแผนเมืองอัจฉริยะเพื่อส่งเสริม การพัฒนาสู่เมืองมหาวิทยาลัยอย่างยั่งยืน ตอนที่ 4',
    },
    {
      id: 57873,
      lecFreeFlag: 0,
      lecId: 57873,
      lecName: 'แบบทดสอบ Urban Infrastructure Plan for Smart City Development',
      lecType: 'QUIZ',
      modId: 10028,
      modOrder: 1,
      title: 'แบบทดสอบ Urban Infrastructure Plan for Smart City Development',
    },
    {
      id: 56263,
      lecFreeFlag: 1,
      lecId: 56263,
      lecName: 'Big Data: Behavior',
      lecType: 'VIDEO',
      modId: 10029,
      modOrder: 2,
      title: 'Big Data: Behavior',
    },
    {
      id: 56264,
      lecFreeFlag: 0,
      lecId: 56264,
      lecName: 'Big Data: Timeline',
      lecType: 'VIDEO',
      modId: 10029,
      modOrder: 2,
      title: 'Big Data: Timeline',
    },
    {
      id: 56265,
      lecFreeFlag: 0,
      lecId: 56265,
      lecName: 'Smart City Focuses',
      lecType: 'VIDEO',
      modId: 10029,
      modOrder: 2,
      title: 'Smart City Focuses',
    },
    {
      id: 56266,
      lecFreeFlag: 0,
      lecId: 56266,
      lecName: 'Data Platform',
      lecType: 'VIDEO',
      modId: 10029,
      modOrder: 2,
      title: 'Data Platform',
    },
    {
      id: 56267,
      lecFreeFlag: 0,
      lecId: 56267,
      lecName: 'Data Governance',
      lecType: 'VIDEO',
      modId: 10029,
      modOrder: 2,
      title: 'Data Governance',
    },
    {
      id: 57867,
      lecFreeFlag: 0,
      lecId: 57867,
      lecName: 'แบบทดสอบ Big Data and Smart City',
      lecType: 'QUIZ',
      modId: 10029,
      modOrder: 2,
      title: 'แบบทดสอบ Big Data and Smart City',
    },
    {
      id: 56273,
      lecFreeFlag: 1,
      lecId: 56273,
      lecName: "What's a smart city in 3 pictures",
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: "What's a smart city in 3 pictures",
    },
    {
      id: 56274,
      lecFreeFlag: 0,
      lecId: 56274,
      lecName: 'What are the domain of smart city',
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: 'What are the domain of smart city',
    },
    {
      id: 56275,
      lecFreeFlag: 0,
      lecId: 56275,
      lecName: 'How to start building a smart city',
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: 'How to start building a smart city',
    },
    {
      id: 56276,
      lecFreeFlag: 0,
      lecId: 56276,
      lecName: 'Design Thinking part 1',
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: 'Design Thinking part 1',
    },
    {
      id: 56277,
      lecFreeFlag: 0,
      lecId: 56277,
      lecName: 'Design Thinking part 2',
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: 'Design Thinking part 2',
    },
    {
      id: 56278,
      lecFreeFlag: 0,
      lecId: 56278,
      lecName: 'Business Model Canvas part 1',
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: 'Business Model Canvas part 1',
    },
    {
      id: 56279,
      lecFreeFlag: 0,
      lecId: 56279,
      lecName: 'Business Model Canvas part 2',
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: 'Business Model Canvas part 2',
    },
    {
      id: 56280,
      lecFreeFlag: 0,
      lecId: 56280,
      lecName: 'Business Model Canvas part 3',
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: 'Business Model Canvas part 3',
    },
    {
      id: 56281,
      lecFreeFlag: 0,
      lecId: 56281,
      lecName: 'Bonus + conclusion',
      lecType: 'VIDEO',
      modId: 10031,
      modOrder: 3,
      title: 'Bonus + conclusion',
    },
    {
      id: 57870,
      lecFreeFlag: 0,
      lecId: 57870,
      lecName: 'แบบทดสอบ Citizens at the Center',
      lecType: 'QUIZ',
      modId: 10031,
      modOrder: 3,
      title: 'แบบทดสอบ Citizens at the Center',
    },
    {
      id: 56268,
      lecFreeFlag: 1,
      lecId: 56268,
      lecName: 'เกริ่นนำ เรื่อง Smart City, Technology and You',
      lecType: 'VIDEO',
      modId: 10030,
      modOrder: 4,
      title: 'เกริ่นนำ เรื่อง Smart City, Technology and You',
    },
    {
      id: 56269,
      lecFreeFlag: 0,
      lecId: 56269,
      lecName: 'Technology for Smart City ช่วงที่ 1',
      lecType: 'VIDEO',
      modId: 10030,
      modOrder: 4,
      title: 'Technology for Smart City ช่วงที่ 1',
    },
    {
      id: 56270,
      lecFreeFlag: 0,
      lecId: 56270,
      lecName: 'Technology for Smart City ช่วงที่ 2',
      lecType: 'VIDEO',
      modId: 10030,
      modOrder: 4,
      title: 'Technology for Smart City ช่วงที่ 2',
    },
    {
      id: 56271,
      lecFreeFlag: 0,
      lecId: 56271,
      lecName: 'Technology for Smart City ช่วงที่ 3',
      lecType: 'VIDEO',
      modId: 10030,
      modOrder: 4,
      title: 'Technology for Smart City ช่วงที่ 3',
    },
    {
      id: 56272,
      lecFreeFlag: 0,
      lecId: 56272,
      lecName: 'Technology for Smart City ช่วงที่ 4',
      lecType: 'VIDEO',
      modId: 10030,
      modOrder: 4,
      title: 'Technology for Smart City ช่วงที่ 4',
    },
    {
      id: 57879,
      lecFreeFlag: 0,
      lecId: 57879,
      lecName: 'แบบทดสอบ Smart City Technology and You',
      lecType: 'QUIZ',
      modId: 10030,
      modOrder: 4,
      title: 'แบบทดสอบ Smart City Technology and You',
    },
    {
      id: 56282,
      lecFreeFlag: 1,
      lecId: 56282,
      lecName:
        'เกริ่นนำ เรื่อง Development Economics and Financial feasibility for Smart City Project',
      lecType: 'VIDEO',
      modId: 10032,
      modOrder: 5,
      title:
        'เกริ่นนำ เรื่อง Development Economics and Financial feasibility for Smart City Project',
    },
    {
      id: 56283,
      lecFreeFlag: 0,
      lecId: 56283,
      lecName: 'เริ่มต้น Project Feasibility',
      lecType: 'VIDEO',
      modId: 10032,
      modOrder: 5,
      title: 'เริ่มต้น Project Feasibility',
    },
    {
      id: 56284,
      lecFreeFlag: 0,
      lecId: 56284,
      lecName: 'ประเมินศักยภาพองค์กร',
      lecType: 'VIDEO',
      modId: 10032,
      modOrder: 5,
      title: 'ประเมินศักยภาพองค์กร',
    },
    {
      id: 56285,
      lecFreeFlag: 0,
      lecId: 56285,
      lecName: 'ประเมินโอกาสทางการตลาด',
      lecType: 'VIDEO',
      modId: 10032,
      modOrder: 5,
      title: 'ประเมินโอกาสทางการตลาด',
    },
    {
      id: 56286,
      lecFreeFlag: 0,
      lecId: 56286,
      lecName: 'ประเมินความคุ้มค่าในการลงทุน',
      lecType: 'VIDEO',
      modId: 10032,
      modOrder: 5,
      title: 'ประเมินความคุ้มค่าในการลงทุน',
    },
    {
      id: 56287,
      lecFreeFlag: 0,
      lecId: 56287,
      lecName: 'การตัดสินใจลงทุน',
      lecType: 'VIDEO',
      modId: 10032,
      modOrder: 5,
      title: 'การตัดสินใจลงทุน',
    },
    {
      id: 57876,
      lecFreeFlag: 0,
      lecId: 57876,
      lecName:
        'แบบทดสอบ Development Economics and Financial feasibility for Smart City Project',
      lecType: 'QUIZ',
      modId: 10032,
      modOrder: 5,
      title:
        'แบบทดสอบ Development Economics and Financial feasibility for Smart City Project',
    },
  ],
  title: 'The Fundamentals of Smart City',
  totalMins: 440,
};

export const categories = [
  {
    id: '1',
    title: 'เตรียมสอบ',
  },
  {
    id: '2',
    title: 'เนื้อหาในห้องเรียน',
  },
  {
    id: '3',
    title: 'ภาษา',
  },
  {
    id: '4',
    title: 'ไอทีและซอร์ฟแวร์',
  },
  {
    id: '5',
    title: 'ธุรกิจและการทำงาน',
  },
  {
    id: '6',
    title: 'ไลฟ์สไตล์',
  },
];

const video = [
  {
    author: 'ทัพพ์วริศ ชิณศิริรัตน์กุล',
    expiriedDate: 1631112612668,
    id: 72,
    image:
      'https://s1-dev.coursesquare.com/data/courses/72/images/coursesquare_cloudtutorial_bootstrapsass.jpg',
    percentage: 0,
    price: 0,
    title: 'สอนใช้ Bootstrap 3 ร่วมกับ Sass',
    totalMins: 105,
  },
  {
    author: 'Smart City Thailand',
    expiriedDate: 1631112612668,
    id: 4312,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4312/images/depa_fun_smart_city_thumbnail.jpg',
    percentage: 6,
    price: 5900,
    title: 'The Fundamentals of Smart City',
    totalMins: 440,
  },
  {
    author: 'ปพน จูน  คิมูระ',
    expiriedDate: 1631112612668,
    id: 4010,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4010/images/paponbook_thumbnail_soceasy.jpg',
    percentage: 0,
    price: 400,
    title: 'Soc Easy สังคมอย่างง่าย แต่ใช้ได้จริง',
    totalMins: 455,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 308,
    image:
      'https://s1-dev.coursesquare.com/data/courses/308/images/coursesquare_wemath_m1t1_realnum.jpg',
    percentage: 0,
    price: 1440,
    title: 'สรุปเข้ม ม.1 ระบบจำนวนเต็ม พร้อมแบบฝึกหัด สสวท.',
    totalMins: 479,
  },
  {
    author: 'เรืออากาศเอก อิศระ เชิดชู',
    expiriedDate: 1631112612668,
    id: 1107,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/1107/images/001-Math.jpg',
    percentage: 0,
    price: 2000,
    title:
      'คู่มือเตรียมสอบคณิตคิดเร็ว ม.ต้น ชุดที่ 1 (บทที่ 1 ถึง 10) l ทดลองเรียนฟรี',
    totalMins: 2738,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4493,
    image:
      'https://s1-dev.coursesquare.com//data/courses/4493/images/4term2_1603258412666.jpg',
    percentage: 0,
    price: 3100,
    title: 'ฟิลิกส์ ม.4 เทอม2',
    totalMins: 0,
  },
  {
    author: 'เรืออากาศเอก อิศระ เชิดชู',
    expiriedDate: 1631112612668,
    id: 1252,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/1252/images/14.jpg',
    percentage: 0,
    price: 1800,
    title:
      'เฉลยข้อสอบเก่าเตรียมทหาร วิชาภาษาอังกฤษ เหล่าทหารอากาศ ย้อนหลัง 7 ปี l ทดลองเรียนฟรี',
    totalMins: 824,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 317,
    image:
      'https://s1-dev.coursesquare.com/data/courses/317/images/coursesquare_wemath-05.jpg',
    percentage: 0,
    price: 530,
    title: 'แบบฝึกหัด สสวท. พร้อมเฉลย ม.2 ความเท่ากันทุกประการ',
    totalMins: 154,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4275,
    image:
      'https://s1-dev.coursesquare.com/data/courses/default/course_default.jpg',
    percentage: 0,
    price: 500,
    title: 'แสงเชิงฟิสิกส์',
    totalMins: 109,
  },
  {
    author: 'เรืออากาศเอก อิศระ เชิดชู',
    expiriedDate: 1631112612668,
    id: 2418,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/2418/images/001.png',
    percentage: 0,
    price: 3000,
    title: 'คณิตศาสตร์เพื่อสอบเตรียมทหาร ม.4 เทอม 1 l ทดลองเรียนฟรี',
    totalMins: 8625,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 320,
    image:
      'https://s1-dev.coursesquare.com/data/courses/320/images/coursesquare_wemath-13.jpg',
    percentage: 0,
    price: 770,
    title: 'สรุปเข้ม ม.3 ระบบสมการเชิงเส้น พร้อมแบบฝึกหัด สสวท.',
    totalMins: 251,
  },
  {
    author: 'อาทิตย์ ฉิมกุล',
    expiriedDate: 1631112612668,
    id: 575,
    image:
      'https://s1-dev.coursesquare.com/data/courses/575/images/Screen Shot 2559-07-23 at 12.27.00 AM.png',
    percentage: 0,
    price: 250,
    title: 'พันธุศาสตร์แสนสนุก Ep.2',
    totalMins: 57,
  },
  {
    author: 'อาทิตย์ ฉิมกุล',
    expiriedDate: 1631112612668,
    id: 552,
    image:
      'https://s1-dev.coursesquare.com/data/courses/552/images/Screen Shot 2559-07-11 at 2.06.40 PM.png',
    percentage: 0,
    price: 250,
    title: 'ตะลุยโจทย์ชีววิทยาพื้นฐานสำหรับผู้เริ่มต้น Ep.1',
    totalMins: 50,
  },
  {
    author: 'Jeffrey Fang',
    expiriedDate: 1631112612668,
    id: 2349,
    image:
      'https://s1-dev.coursesquare.com/data/courses/2349/images/A9649C97-0E1F-49A0-93B6-E4F6BFD9D62A.jpeg',
    percentage: 0,
    price: 250,
    title: 'ภาษาจีน คุยได้ตอบเป็น 1',
    totalMins: 42,
  },
  {
    author: 'กวดวิชา กับพี่ควายน้อย',
    expiriedDate: 1631112612668,
    id: 1158,
    image: 'https://s1-dev.coursesquare.com/data/courses/1158/images/ปก.jpg',
    percentage: 0,
    price: 649,
    title: 'เซต ชั้นมัธยมศึกษาปีที่ 4',
    totalMins: 199,
  },
  {
    author: 'TewEz Physics',
    expiriedDate: 1631112612668,
    id: 1505,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1505/images/ติวง่ายฟิสิกส์ กฏ แรง มวล.jpg',
    percentage: 0,
    price: 690,
    title: 'ติวง่ายฟิสิกส์ แรง มวล และกฏการเคลื่อนที่',
    totalMins: 156,
  },
  {
    author: 'เรืออากาศเอก อิศระ เชิดชู',
    expiriedDate: 1631112612668,
    id: 399,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/399/images/Untitled.png',
    percentage: 0,
    price: 2100,
    title:
      'เฉลยข้อสอบเก่าเตรียมทหาร วิชาภาษาอังกฤษ เหล่าทหารบก ย้อนหลัง 10 ปี l ทดลองเรียนฟรี',
    totalMins: 1109,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 321,
    image:
      'https://s1-dev.coursesquare.com/data/courses/321/images/coursesquare_wemath-14.jpg',
    percentage: 0,
    price: 720,
    title: 'สรุปเข้ม ม.3 ความคล้าย พร้อมแบบฝึกหัด สสวท.',
    totalMins: 246,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4272,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4272/images/13 แสงและทัศนอุปกรณ์.jpg',
    percentage: 0,
    price: 600,
    title: 'แสงและทัศนอุปกรณ์',
    totalMins: 765,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4284,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4284/images/16 แม่เหล็กไฟฟ้า.jpg',
    percentage: 0,
    price: 600,
    title: 'แม่เหล็กไฟฟ้า',
    totalMins: 785,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4266,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4266/images/11 คลื่น.jpg',
    percentage: 0,
    price: 600,
    title: 'คลื่น',
    totalMins: 839,
  },
  {
    author: 'เรืออากาศเอก อิศระ เชิดชู',
    expiriedDate: 1631112612668,
    id: 422,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/422/images/13.jpg',
    percentage: 0,
    price: 1800,
    title:
      'เฉลยข้อสอบเก่าเตรียมทหาร วิชาภาษาอังกฤษ เหล่าทหารเรือ ย้อนหลัง 6 ปี l ทดลองเรียนฟรี',
    totalMins: 708,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 315,
    image:
      'https://s1-dev.coursesquare.com/data/courses/315/images/coursesquare_wemath-08.jpg',
    percentage: 0,
    price: 680,
    title: 'สรุปเข้ม ม.2 การแปลงทางเรขาคณิต พร้อมแบบฝึกหัด สสวท.',
    totalMins: 164,
  },
  {
    author: 'เรืออากาศเอก อิศระ เชิดชู',
    expiriedDate: 1631112612668,
    id: 612,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/612/images/16.jpg',
    percentage: 0,
    price: 2100,
    title:
      'เฉลยข้อสอบเก่าโครงการช้างเผือก วิชาภาษาอังกฤษ ย้อนหลัง 7 ปี l ทดลองเรียนฟรี',
    totalMins: 539,
  },
  {
    author: 'พี่ณัฐ iSMILE (อ.ณัฐพล สรรพกิจกำจร)',
    expiriedDate: 1631112612668,
    id: 1162,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1162/images/Untitled-2.jpg',
    percentage: 0,
    price: 900,
    title: 'ฟิสิกส์ กลุ่มคลื่น เรื่องเสียง',
    totalMins: 730,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 312,
    image:
      'https://s1-dev.coursesquare.com/data/courses/312/images/coursesquare_wemath-06.jpg',
    percentage: 0,
    price: 900,
    title: 'สรุปเข้ม ม.2 การวัด พร้อมแบบฝึกหัด สสวท.',
    totalMins: 300,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 307,
    image:
      'https://s1-dev.coursesquare.com/data/courses/307/images/coursesquare_wemath_m1t1_gcdlcm.jpg',
    percentage: 0,
    price: 900,
    title: 'สรุปเข้ม ม.1 ห.ร.ม., ค.ร.น. พร้อมแบบฝึกหัด สสวท.',
    totalMins: 295,
  },
  {
    author: 'อาจารย์จิรฐา อัคนิทัต',
    expiriedDate: 1631112612668,
    id: 1977,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1977/images/swot-analysis-stebcourse.png',
    percentage: 0,
    price: 500,
    title: 'SWOT Analysis วิเคราะห์ธุรกิจเพื่อก้าวสู่ยุคของการปรับตัว',
    totalMins: 42,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4287,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4287/images/17 ไฟฟ้ากระแสสลับ.jpg',
    percentage: 0,
    price: 500,
    title: 'ไฟฟ้ากระแสสลับ',
    totalMins: 477,
  },
  {
    author: 'พี่สิริ วงศ์วรชาติกาล',
    expiriedDate: 1631112612668,
    id: 4655,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4655/images/tutorsiri_course_thumbnail-03.jpg',
    percentage: 0,
    price: 5000,
    title: 'แพ็คคู่เก็งข้อสอบ PAT1 และ ตะลุยโจทย์สามัญ',
    totalMins: 5153,
  },
  {
    author: 'MU Tutor',
    expiriedDate: 1631112612668,
    id: 1583,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1583/images/หน้าปก ขูวิทย์ เคมี อ.มิค-01.jpg',
    percentage: 0,
    price: 3200,
    title: 'ชูวิทย์เคมี',
    totalMins: 1950,
  },
  {
    author: 'Course Square',
    expiriedDate: 1631112612668,
    id: 4649,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4649/images/TN-EngforPres.jpg',
    percentage: 0,
    price: 3000,
    title: 'English For High Impact Presentations',
    totalMins: 188,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4648,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4648/images/TN-Business-Planning-3.jpg',
    percentage: 0,
    price: 3000,
    title: 'Business Planning วางแผนธุรกิจให้ครบและโดนใจอย่างมืออาชีพ',
    totalMins: 140,
  },
  {
    author: 'เรืออากาศเอก อิศระ เชิดชู',
    expiriedDate: 1631112612668,
    id: 422,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/422/images/13.jpg',
    percentage: 0,
    price: 1800,
    title:
      'เฉลยข้อสอบเก่าเตรียมทหาร วิชาภาษาอังกฤษ เหล่าทหารเรือ ย้อนหลัง 6 ปี l ทดลองเรียนฟรี',
    totalMins: 708,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 310,
    image:
      'https://s1-dev.coursesquare.com/data/courses/310/images/coursesquare_wemath_m1t1_geometry.jpg',
    percentage: 0,
    price: 990,
    title: 'สรุปเข้ม ม.1 พื้นฐานทางเรขาคณิต พร้อมแบบฝึกหัด สสวท.',
    totalMins: 330,
  },
  {
    author: 'K.I.W Q',
    expiriedDate: 1631112612668,
    id: 1210,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1210/images/เมทริกซ์ ปกติ.jpg',
    percentage: 0,
    price: 900,
    title: 'จบกันที เมทริกซ์',
    totalMins: 329,
  },
  {
    author: 'กฤษฎ์กำพล ภูวัชร์เดชพงศ์',
    expiriedDate: 1631112612668,
    id: 2758,
    image:
      'https://s1-dev.coursesquare.com/data/courses/default/course_garuda.jpg',
    percentage: 0,
    price: 900,
    title: 'ตะลุยโจทย์ของไหล',
    totalMins: 204,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 312,
    image:
      'https://s1-dev.coursesquare.com/data/courses/312/images/coursesquare_wemath-06.jpg',
    percentage: 0,
    price: 900,
    title: 'สรุปเข้ม ม.2 การวัด พร้อมแบบฝึกหัด สสวท.',
    totalMins: 300,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 307,
    image:
      'https://s1-dev.coursesquare.com/data/courses/307/images/coursesquare_wemath_m1t1_gcdlcm.jpg',
    percentage: 0,
    price: 900,
    title: 'สรุปเข้ม ม.1 ห.ร.ม., ค.ร.น. พร้อมแบบฝึกหัด สสวท.',
    totalMins: 295,
  },
  {
    author: 'กวดวิชา กับพี่ควายน้อย',
    expiriedDate: 1631112612668,
    id: 1158,
    image: 'https://s1-dev.coursesquare.com/data/courses/1158/images/ปก.jpg',
    percentage: 0,
    price: 649,
    title: 'เซต ชั้นมัธยมศึกษาปีที่ 4',
    totalMins: 199,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 315,
    image:
      'https://s1-dev.coursesquare.com/data/courses/315/images/coursesquare_wemath-08.jpg',
    percentage: 0,
    price: 680,
    title: 'สรุปเข้ม ม.2 การแปลงทางเรขาคณิต พร้อมแบบฝึกหัด สสวท.',
    totalMins: 164,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 317,
    image:
      'https://s1-dev.coursesquare.com/data/courses/317/images/coursesquare_wemath-05.jpg',
    percentage: 0,
    price: 530,
    title: 'แบบฝึกหัด สสวท. พร้อมเฉลย ม.2 ความเท่ากันทุกประการ',
    totalMins: 154,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 317,
    image:
      'https://s1-dev.coursesquare.com/data/courses/317/images/coursesquare_wemath-05.jpg',
    percentage: 8,
    price: 530,
    title: 'แบบฝึกหัด สสวท. พร้อมเฉลย ม.2 ความเท่ากันทุกประการ',
    totalMins: 154,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4266,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4266/images/11 คลื่น.jpg',
    percentage: 0,
    price: 600,
    title: 'คลื่น',
    totalMins: 839,
  },
  {
    author: 'ปพน จูน  คิมูระ',
    expiriedDate: 1631112612668,
    id: 1135,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1135/images/paponbook_thumbnail_socwork_package.jpg',
    percentage: 0,
    price: 400,
    title: 'SocWork Package เตรียมสอบความถนัดคณะสังคมสงเคราะห์ศาสตร์',
    totalMins: 135,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4539,
    image:
      'https://s1-dev.coursesquare.com//data/courses/4539/images/9_วิชา_1605156157798.jpg',
    percentage: 0,
    price: 300,
    title: 'เฉลย 9 วิชาสามัญ ปี2556',
    totalMins: 0,
  },
  {
    author: 'กวดวิชา กับพี่ควายน้อย',
    expiriedDate: 1631112612668,
    id: 1158,
    image: 'https://s1-dev.coursesquare.com/data/courses/1158/images/ปก.jpg',
    percentage: 0,
    price: 649,
    title: 'เซต ชั้นมัธยมศึกษาปีที่ 4',
    totalMins: 199,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612668,
    id: 315,
    image:
      'https://s1-dev.coursesquare.com/data/courses/315/images/coursesquare_wemath-08.jpg',
    percentage: 0,
    price: 680,
    title: 'สรุปเข้ม ม.2 การแปลงทางเรขาคณิต พร้อมแบบฝึกหัด สสวท.',
    totalMins: 164,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4284,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4284/images/16 แม่เหล็กไฟฟ้า.jpg',
    percentage: 0,
    price: 600,
    title: 'แม่เหล็กไฟฟ้า',
    totalMins: 785,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4296,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4296/images/20 ความร้อนและทฤษฎีจนล์แก๊ส.jpg',
    percentage: 0,
    price: 600,
    title: 'ความร้อนและทฤษฎีจลน์ของแก๊ส',
    totalMins: 629,
  },
  {
    author: ' ',
    expiriedDate: 1631112612668,
    id: 4299,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4299/images/21 ฟิสิกส์อะตอม.jpg',
    percentage: 0,
    price: 600,
    title: 'ฟิสิกส์อะตอม',
    totalMins: 443,
  },
  {
    author: 'เรืออากาศเอก อิศระ เชิดชู',
    expiriedDate: 1631112612668,
    id: 414,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/414/images/3.jpg',
    percentage: 0,
    price: 0,
    title: 'ฟิสิกส์เพื่อสอบเตรียมทหาร l เรียนฟรี',
    totalMins: 668,
  },
  {
    author: 'พี่ณัฐ iSMILE (อ.ณัฐพล สรรพกิจกำจร)',
    expiriedDate: 1631112612668,
    id: 1169,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1169/images/Untitled-3.jpg',
    percentage: 0,
    price: 200,
    title: 'ฟิสิกส์ กลศาสตร์ 1 บทที่ 1 เรื่องบทนำ',
    totalMins: 217,
  },
  {
    author: 'K.I.W Q',
    expiriedDate: 1631112612668,
    id: 1218,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1218/images/จำนวนเชิงซ้อน.jpg',
    percentage: 0,
    price: 900,
    title: 'จบกันที จำนวนเชิงซ้อน',
    totalMins: 414,
  },
  {
    author: 'Idea Trade',
    expiriedDate: 1631112612668,
    id: 283,
    image:
      'https://s1-dev.coursesquare.com/data/courses/tmp/coursesquare_ideatrade_weeklystockmarket.jpg',
    percentage: 0,
    price: 0,
    title: 'การวิเคราะห์ตลาดหุ้น รายสัปดาห์',
    totalMins: 431,
  },
  {
    author: 'กวดวิชา กับพี่ควายน้อย',
    expiriedDate: 1631112612669,
    id: 1156,
    image: 'https://s1-dev.coursesquare.com/data/courses/1156/images/12.jpg',
    percentage: 0,
    price: 569,
    title: 'อัตราส่วนและร้อยละ ชั้นมัธยมศึกษาปีที่ 2',
    totalMins: 178,
  },
  {
    author: 'ปพน จูน  คิมูระ',
    expiriedDate: 1631112612669,
    id: 1181,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1181/images/paponbook_thumbnail_socialquick.jpg',
    percentage: 0,
    price: 300,
    title: 'Social Quick สรุปสังคมศึกษา ม.ปลาย',
    totalMins: 176,
  },
  {
    author: 'Nikki Changsanoh',
    expiriedDate: 1631112612669,
    id: 699,
    image:
      'https://s1-dev.coursesquare.com/data/courses/699/images/promo_01.png',
    percentage: 0,
    price: 0,
    title: 'เตรียมความพร้อมเป็นผู้ส่งออกมืออาชีพ',
    totalMins: 26,
  },
  {
    author: ' ',
    expiriedDate: 1631112612669,
    id: 4290,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/4290/images/18 คลื่นแม่เหล็กไฟฟ้า.jpg',
    percentage: 0,
    price: 300,
    title: 'คลื่นแม่เหล็กไฟฟ้า',
    totalMins: 150,
  },
  {
    author: 'อนพัทย์ พิพัฒน์กิติบดี',
    expiriedDate: 1631112612669,
    id: 353,
    image:
      'https://s1-dev.coursesquare.com/data/courses/353/images/STelligenceWorkshop-08.jpg',
    percentage: 0,
    price: 0,
    title:
      'Splunk Workshop Driven Value of Your Data  to Real Time IT Operation Analytic',
    totalMins: 101,
  },
  {
    author: 'K.I.W Q',
    expiriedDate: 1631112612669,
    id: 1215,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1215/images/Expolog.jpg',
    percentage: 0,
    price: 1400,
    title: 'จบกันที ExpoLog',
    totalMins: 638,
  },
  {
    author: 'K.I.W Q',
    expiriedDate: 1631112612669,
    id: 1216,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1216/images/ตรีโกณมิติ.jpg',
    percentage: 0,
    price: 1400,
    title: 'จบกันที ตรีโกณมิติ',
    totalMins: 666,
  },
  {
    author: ' ',
    expiriedDate: 1631112612669,
    id: 4305,
    image:
      'https://s1-dev.coursesquare.com//data/courses/4305/images/4term1_1_1603257282003.jpg',
    percentage: 0,
    price: 1700,
    title: 'ฟิสิกส์ ม.4 เทอม1',
    totalMins: 0,
  },
  {
    author: 'Thailand Tech Startup Association ',
    expiriedDate: 1631112612669,
    id: 288,
    image:
      'https://s1-dev.coursesquare.com/data/courses/288/images/coursesquare_tcdc_thdigitaleco.jpg',
    percentage: 0,
    price: 0,
    title: 'Thailand Digital Economy by TCDC',
    totalMins: 181,
  },
  {
    author: 'Morakot Choetkiertikul',
    expiriedDate: 1631112612669,
    id: 12,
    image: 'https://s1-dev.coursesquare.com/data/courses/12/images/display.jpg',
    percentage: 0,
    price: 0,
    title: 'เริ่มเขียนโปรแกรมง่ายๆ ด้วยภาษาซี',
    totalMins: 52,
  },
  {
    author: 'Sketch Users Thailand',
    expiriedDate: 1631112612669,
    id: 341,
    image:
      'https://s1-dev.coursesquare.com/data/courses/341/images/sketch-meetup-thailand.jpg',
    percentage: 0,
    price: 0,
    title: 'Sketch Meetup Thailand',
    totalMins: 150,
  },
  {
    author: 'Apirak Panatkool',
    expiriedDate: 1631112612669,
    id: 73,
    image:
      'https://s1-dev.coursesquare.com/data/courses/73/images/uxacademy_uxtalk.jpg',
    percentage: 0,
    price: 0,
    title: 'UX Talk ตอน E Commerce แบบไทยๆ',
    totalMins: 198,
  },
  {
    author: 'Nikki Changsanoh',
    expiriedDate: 1631112612669,
    id: 700,
    image:
      'https://s1-dev.coursesquare.com/data/courses/700/images/promo_02.png',
    percentage: 0,
    price: 499,
    title: 'INCO TERM ในการส่งออก',
    totalMins: 26,
  },
  {
    author: ' ',
    expiriedDate: 1631112612669,
    id: 2795,
    image:
      'https://s1-dev.coursesquare.com/data/uploads/courses/2795/images/japaneseLv1.jpg',
    percentage: 0,
    price: 500,
    title: 'ภาษาญึ่ปุ่น Level 1 สำหรับผู้เริ่มต้น',
    totalMins: 36,
  },
  {
    author: 'นักรบ ธุรกิจ',
    expiriedDate: 1631112612669,
    id: 28,
    image: 'https://s1-dev.coursesquare.com/data/courses/28/images/display.jpg',
    percentage: 0,
    price: 0,
    title: 'พื้นฐานการใช้งาน Wordpress ทั้งหมด (WP102)',
    totalMins: 174,
  },
  {
    author: 'K.I.W Q',
    expiriedDate: 1631112612669,
    id: 1206,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1206/images/Real number.jpg',
    percentage: 0,
    price: 1400,
    title: 'จบกันที ระบบจำนวนจริง',
    totalMins: 568,
  },
  {
    author: 'สุวิชญา สุทสว่างวงศ์ (พี่กิ๊ฟท์)',
    expiriedDate: 1631112612669,
    id: 2326,
    image:
      'https://s1-dev.coursesquare.com/data/courses/2326/images/workshop-gat.png',
    percentage: 0,
    price: 690,
    title: 'ติวเข้มข้นข้อสอบ GAT อัปคะแนนพาร์ทอังกฤษ ปิดจุดอ่อนพาร์ทเชื่อมโยง',
    totalMins: 340,
  },
  {
    author: 'TewEz Physics',
    expiriedDate: 1631112612669,
    id: 1484,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1484/images/ติวง่ายฟิสิกส์ การเคลื่อนที่แนวตรง.jpg',
    percentage: 0,
    price: 690,
    title: 'ติวง่ายฟิสิกส์ การเคลื่อนที่แนวตรง',
    totalMins: 200,
  },
  {
    author: 'TewEz Physics',
    expiriedDate: 1631112612669,
    id: 1505,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1505/images/ติวง่ายฟิสิกส์ กฏ แรง มวล.jpg',
    percentage: 0,
    price: 690,
    title: 'ติวง่ายฟิสิกส์ แรง มวล และกฏการเคลื่อนที่',
    totalMins: 156,
  },
  {
    author: 'Jeffrey Fang',
    expiriedDate: 1631112612669,
    id: 2349,
    image:
      'https://s1-dev.coursesquare.com/data/courses/2349/images/A9649C97-0E1F-49A0-93B6-E4F6BFD9D62A.jpeg',
    percentage: 0,
    price: 250,
    title: 'ภาษาจีน คุยได้ตอบเป็น 1',
    totalMins: 42,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612669,
    id: 316,
    image:
      'https://s1-dev.coursesquare.com/data/courses/316/images/coursesquare_wemath-10.jpg',
    percentage: 0,
    price: 0,
    title: 'สรุปเข้ม ม.2 ความเท่ากันทุกประการ',
    totalMins: 31,
  },
  {
    author: 'กวดวิชา กับพี่ควายน้อย',
    expiriedDate: 1631112612669,
    id: 1156,
    image: 'https://s1-dev.coursesquare.com/data/courses/1156/images/12.jpg',
    percentage: 0,
    price: 569,
    title: 'อัตราส่วนและร้อยละ ชั้นมัธยมศึกษาปีที่ 2',
    totalMins: 178,
  },
  {
    author: ' ',
    expiriedDate: 1631112612669,
    id: 4275,
    image:
      'https://s1-dev.coursesquare.com/data/courses/default/course_default.jpg',
    percentage: 0,
    price: 500,
    title: 'แสงเชิงฟิสิกส์',
    totalMins: 109,
  },
  {
    author: 'ปพน จูน  คิมูระ',
    expiriedDate: 1631112612669,
    id: 1181,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1181/images/paponbook_thumbnail_socialquick.jpg',
    percentage: 0,
    price: 300,
    title: 'Social Quick สรุปสังคมศึกษา ม.ปลาย',
    totalMins: 176,
  },
  {
    author: 'พี่ณัฐ iSMILE (อ.ณัฐพล สรรพกิจกำจร)',
    expiriedDate: 1631112612669,
    id: 1168,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1168/images/Untitled-3.jpg',
    percentage: 0,
    price: 200,
    title: 'ฟิสิกส์ กลศาสตร์ 1 เรื่องบทนำ',
    totalMins: 217,
  },
  {
    author: 'อ.พุทธ วิชญกาญจน์กุล',
    expiriedDate: 1631112612669,
    id: 4660,
    image:
      'https://s1-dev.coursesquare.com//data/courses/4660/images/selfmanagedteam_1614076220501.jpg',
    percentage: 0,
    price: 1299,
    title: 'Self managed Team พัฒนาทีมให้มีประสิทธิภาพ',
    totalMins: 32,
  },
  {
    author: 'พี่ณัฐ iSMILE (อ.ณัฐพล สรรพกิจกำจร)',
    expiriedDate: 1631112612669,
    id: 1161,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1161/images/Untitled-1.jpg',
    percentage: 0,
    price: 4900,
    title: 'ฟิสิกส์ Entrance 4.0',
    totalMins: 3090,
  },
  {
    author: 'K.I.W Q',
    expiriedDate: 1631112612669,
    id: 1212,
    image:
      'https://s1-dev.coursesquare.com/data/courses/1212/images/ฟังก์ชัน ปกติ.jpg',
    percentage: 0,
    price: 900,
    title: 'จบกันที ฟังก์ชัน',
    totalMins: 386,
  },
  {
    author: 'ณัฐพัชร์ อุบลรัตน์ (อ.สันต์)',
    expiriedDate: 1631112612669,
    id: 310,
    image:
      'https://s1-dev.coursesquare.com/data/courses/310/images/coursesquare_wemath_m1t1_geometry.jpg',
    percentage: 0,
    price: 990,
    title: 'สรุปเข้ม ม.1 พื้นฐานทางเรขาคณิต พร้อมแบบฝึกหัด สสวท.',
    totalMins: 330,
  },
  {
    author: 'ภัทรธร ช่อวิชิต',
    expiriedDate: 1631112612669,
    id: 282,
    image:
      'https://s1-dev.coursesquare.com/data/courses/282/images/coursesquare_investidea_businesssecret.jpg',
    percentage: 0,
    price: 1500,
    title: 'แกะรอยธุรกิจแตกผ่านงบการเงิน',
    totalMins: 226,
  },
  {
    author: 'อาทิตย์ ฉิมกุล',
    expiriedDate: 1631112612669,
    id: 575,
    image:
      'https://s1-dev.coursesquare.com/data/courses/575/images/Screen Shot 2559-07-23 at 12.27.00 AM.png',
    percentage: 0,
    price: 250,
    title: 'พันธุศาสตร์แสนสนุก Ep.2',
    totalMins: 57,
  },
  {
    author: 'อาทิตย์ ฉิมกุล',
    expiriedDate: 1631112612669,
    id: 559,
    image:
      'https://s1-dev.coursesquare.com/data/courses/559/images/Screen Shot 2559-07-23 at 12.24.22 PM.png',
    percentage: 0,
    price: 250,
    title: 'พันธุศาสตร์แสนสนุก Ep.1',
    totalMins: 36,
  },
  {
    author: 'สมเกียรติ ปุ๋ยสูงเนิน',
    expiriedDate: 1631112612669,
    id: 342,
    image:
      'https://s1-dev.coursesquare.com/data/courses/342/images/coursesquare_thaiprogrammer_elasticsearch.jpg',
    percentage: 0,
    price: 0,
    title: 'โค้ดชิวๆกับ Elasticsearch',
    totalMins: 131,
  },
  {
    author: 'วุฒิพงศ์ นิ่มอ่อน',
    expiriedDate: 1631112612669,
    id: 292,
    image:
      'https://s1-dev.coursesquare.com/data/courses/292/images/photoshopcc.jpg',
    percentage: 4,
    price: 0,
    title: 'Photoshop CC 2014 For Photographer',
    totalMins: 139,
  },
];
